âžœ sh run_kubernetes.sh
Error from server (AlreadyExists): pods "ml-flask-api" already exists
NAME           READY   STATUS    RESTARTS   AGE
ml-flask-api   1/1     Running   0          4m27s
POD status is Running
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
^C * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 327-038-927
[2020-10-21 17:07:11,127] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2020-10-21 17:07:11,197] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-10-21 17:07:11,228] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-10-21 17:07:11,242] INFO in app: Prediction: [20.35373177134412]
127.0.0.1 - - [21/Oct/2020 17:07:11] "POST /predict HTTP/1.1" 200 -